### ISSUE TITLE
A tool bar for drawing various shapes

### ISSUE THREAD

**Issue by shaunakv1** [symbioquine/ol-touch-draw#1]
Hi first up, thanks for great work on this. Is it a possibility to support adding a toolbar control for supporting various shapes on the map? Something on the lines of: 

http://viglino.github.io/ol-ext/examples/bar/map.control.editionbar.html

**Comment by symbioquine** [comment]
Thanks! It's definitely possible and I agree it would be good to support more types of shapes beyond just orthogonal rectangles.

That said, my inclination with this library would be to keep it fairly low-level in terms of implementing the actual "touch draw" interactions, but not making assumptions about how they should be integrated into a larger map-based application. In other words, this library should include support for other shapes eventually, but probably shouldn't directly provide the toolbar part.

My reason for authoring this library is to enhance mobile drawing for [farmOS](https://farmos.org/), in that context my understanding is that one of the most common use-cases is drawing new rectangular beds/fields/etc which are orthogonal to existing beds/fields/etc. I hope that the library will be useful to others of course, but the farmOS use-case is my primary focus.

I would be happy to entertain pull requests to implement other "touch drawing" interaction scenarios, but I probably won't be expanding it arbitrarily in the near future myself.
